version: "3"
services:

  microservice-mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db-data
    
  microservice-web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - microservice-mongo

volumes:
  db-data: